### 服务启动端口号
server:
  port: 10200
  servlet:
    context-path: /serviceInformation

###服务名称(注册到eureka的名称)
spring:
  application:
    name: peiyou-service-information

###服务注册到eureka
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
  instance:
    metadata-map:
      context-path: ${server.servlet.context-path}
      health-check-url: http://localhost:${server.port}/gateway/actuator/health
      status-page-url: http://localhost:${server.port}/gateway/actuator/info
      home-page-url: http://localhost:${server.port}/


###swagger
swagger:
  base-package: com.peiyou.controller
  title: 培优小课堂-后台管理系统
  description: 该项目提供给培优小课堂的后台管理系统调用
  version: 1.0